twilio/voice-quickstart-ios

- Podfile
- SwiftVoiceQuickstart/AppDelegate.swift
- SwiftVoiceQuickstart/ViewController.swift
- Improve UI logics
- Update Podfile for beta4 artifact
> Update for beta4

- Podfile
- README.md
- SwiftVoiceCallKitQuickstart.xcodeproj/project.pbxproj
- SwiftVoiceCallKitQuickstart/AppDelegate.swift
- SwiftVoiceCallKitQuickstart/ViewController.swift
- SwiftVoiceQuickstart.xcodeproj/project.pbxproj
- SwiftVoiceQuickstart/AppDelegate.swift
- SwiftVoiceQuickstart/ViewController.swift
- Update `Podfile` with the latest framework name and version
- Update project settings
- `VoiceClient` -> `TwilioVoice` in the source code
- Remove `client` in the README
> Update for 2.0.0-beta8 release

- Podfile
- SwiftVoiceCallKitQuickstart/ViewController.swift
- Bump podspec to use 2.0.0-beta11
- Add audioSessionDeactivated in the provider:didDeactivateAudioSession: callback
- Update delegate method signature
> Update for Voice 2.0.0-beta11

- README.md
* Mention Plaintext requirements
* Mention the information that must be provided with each blob of text.
I'm submitting this PR because it solves/answers what was asked in the help desk ticket # 950136
> Push Certificate Documentation additions

- SwiftVoiceCallKitQuickstart.xcodeproj/project.pbxproj
- SwiftVoiceQuickstart.xcodeproj/project.pbxproj
Same as: https://github.com/twilio/voice-quickstart-objc/pull/46
* Let CocoaPods do this at install time, and support manual integration.
> Remove CocoaPods from the Xcode projects.

- Podfile
- SwiftVoiceCallKitQuickstart/ViewController.swift
- Update podspec reference to beta16
- Update `CallKitIntegration` methods to reflect changes introduced in beta16
> Update for Voice 2.0.0-beta16 release

- Podfile
- SwiftVoiceCallKitQuickstart/AppDelegate.swift
- SwiftVoiceCallKitQuickstart/ViewController.swift
- SwiftVoiceQuickstart/AppDelegate.swift
- SwiftVoiceQuickstart/ViewController.swift
- Use `beta19` in Podfile
- `sharedInstance` is removed from `TwilioVoice`
- Update `TVOCallDelegate` methods
> Updates for Voice 2.0.0-beta19 release

- Podfile
- SwiftVoiceCallKitQuickstart/ViewController.swift
- Bump to beta20
- Update properties to reflect nullability contract changes
> Update for Voice 2.0.0-beta20 release

- Podfile
- SwiftVoiceCallKitQuickstart/ViewController.swift
- SwiftVoiceQuickstart/ViewController.swift
- Bump `Podfile` version.
- API updates
- `TwilioVoice.startAudio()` & `TwilioVoice.stopAudio()` are replaced by the new property `TwilioVoice.audioEnabled`.
> Updates for Voice 2.0.0-beta22 release

- SwiftVoiceCallKitQuickstart/ViewController.swift
Audio should be disable before accepting the call to ensure the call has good audio.
> Audio should be disabled before answering the call

- README.md
Addressing https://github.com/twilio/voice-quickstart-swift/issues/95
> Add note about membership requirement

- README.md
- Add more language supports for server quickstart
- Update pseudo URL
> Update README with more server quickstarts

- README.md
Add audio interruptions handling guide to README.
- Describe how the Voice SDK works during AVAudioSesison interruptions.
- List of notifications and observations during audio interruptions.
- CallKit.
> Add audio interruption handling guide to README

- README.md
This is for pulling the images into the CMS. Thanks!
> Updated relative image URLs to absolute image URLs

- Podfile
- README.md
- Update `Podfile`
- Update artifact link in `README.md`
> Update for Voice 3.0.0-preview4 release

- README.md
- Add a new section for new features
- Update links
> Add New Features section in README

- Podfile
- README.md
- Use Voice iOS `3.0.0-beta2`
- Add sample code for specifying preferred audio codec
> Update for 3.0.0-beta2 release

- Cartfile
- Podfile
- README.md
Enhancements
- CLIENT-5258 Reduced SDK size by stripping video software codecs.
- CLIENT-5353 Reduced SDK size by stripping SCTP data channels.
Known Issues
Size Report
> Use 3.0.0-beta6

- Cartfile
- Podfile
- README.md
Enhancements
- CLIENT-5379 Added network reachability monitoring for the signaling socket for a reliable network change detection.
Bug Fixes
- CLIENT-5379 Fixed a bug where WiFi to WiFi network hand off was causing one-way audio followed by Call disconnect.
Known Issues
Size Report
> Use Voice iOS SDK 3.0.0-beta11

- README.md
README note to use master for 3.x APIs
> README note to use master for 3.x APIs

- Cartfile
- Podfile
- README.md
- SwiftVoiceCallKitQuickstart.xcodeproj/project.pbxproj
- SwiftVoiceCallKitQuickstart/ViewController.swift
- SwiftVoiceQuickstart.xcodeproj/project.pbxproj
- SwiftVoiceQuickstart/ViewController.swift
Known Issues
Size Report
Universal | 5.8 MB | 12.3 MB
> Updates for Voice iOS 3.0.0 release

- README.md
> Add 3.0 notice

- README.md
> Update 2.x sunset notice

- Docs/new-features-3.0.md
Update docs and code snippet using Opus as the default codec
> Update preferred audio codec guide

- Docs/new-features-4.0.md
- README.md
New feature guide for Voice iOS 4.0
- Add a new documentation markdown for new features in 4.0
- Add an entry to the 4.0 new feature guide in README
> New feature of 4.0

- Docs/migration-guide-3.x-4.x.md
- Docs/new-features-4.0.md
- README.md
Migration guide and new features of 4.0
> Separate migration guide from new features

- README.md
Also for the Updating Push Credentials Image.
> Update README with absolute URLs for Docs

- README.md
> Fix URL for Updating Push Credentials Image

- Podfile
> Releasing 4.1.0

- Cartfile
- Podfile
The Differentiated Services Code Point (DSCP) Tagging API allows you to mark the audio packets with Expedited Forwarding (EF) for the purposes of improved packet routing. When enabled, supporting networks will prioritize audio packet delivery for improved audio quality.
Use `enableDscp` to enable or disable DSCP tagging. Note, `enableDscp` is enabled by default.
For example:
```swift
// Configure DSCP with `TVOConnectOptions`
let connectOptions = TVOConnectOptions(accessToken: accessToken) { (builder) in
builder.enableDscp = true
}
let call = TwilioVoice.connect(with: connectOptions, delegate: callDelegate)
```
```swift
// Configure DSCP with `TVOAcceptOptions`
let acceptOptions = TVOAcceptOptions(accessToken: accessToken) { (builder) in
builder.enableDscp = true
}
let call = …
```
> Use Voice iOS 4.3.0

- README.md
The TwiML Apps have moved in the console
Update TwiML App URL
> Fixed twiml app url

- Docs/migration-guide-2.x-3.x.md
One of code block of migration guide is not highlighted with swift, I fixed it.
> Use syntax highlight of code block

- SwiftVoiceQuickstart/Base.lproj/Main.storyboard
The method of IBAction of the main button was updated in the previous PR but the storyboard update was not committed.
> Update IBAction link in the storyboard

- Cartfile
- Podfile
Enhancements
- Application name, bundle ID, version, build number, Xcode version and min/major SDK version are now published to Insights. This helps with isolating problems if an issue is encountered.
Universal | 6.0 MB | 12.6 MB
> Use Voice iOS 5.1.1

- ObjcVoiceQuickstart/ViewController.m
Use adaptive length for PushKit device token decoding for future-proof.
> Update PushKit device token decoding to take adaptive length

- Podfile
Bug Fixes
- Fixed duplicated symbol linker errors in the static library.
> Use Voice iOS 5.2.1

- Podfile
> Use Voice iOS 5.4.0

- Podfile
> Use Voice iOS 5.4.1

- Podfile
> Using TwilioVoice 5.5.0

- README.md
I sort of guessed what it needs to be updated to. Can you please validate?
> Updating 404 link on the docs site

- README.md
> Added iOS 14 note in README

- AudioDeviceExample/ViewController.swift
- ObjcVoiceQuickstart/ViewController.m
- SwiftVoiceQuickstart/ViewController.swift
- Adopt new Swifty API names
- Audio device updates
> Adopt new Swift API names of Voice iOS 6.0

- Docs/migration-guide-5.x-6.x.md
> Migration guide 5.x to 6.x

- Podfile
Bug Fixes
- Fixed Swift compile time error for `AudioDeviceContext`.
Size Impact for 6.0.1
Universal | 3.1 MB | 6.8 MB
arm64 | 3.1 MB | 6.8 MB
> Use Voice iOS 6.0.1

- Podfile
Bug Fixes
- Fixed Swift compile time error for `AudioDeviceWorkerBlock`.
Size Impact for 6.0.2
Universal | 3.1 MB | 6.8 MB
arm64 | 3.1 MB | 6.8 MB
> Voice iOS 6.0.2

- Server/package-lock.json
- Server/package.json
- Ran `npm audit fix` and update vulnerable dependencies
> Update dependencies to fix vulnerability

- ObjcVoiceQuickstart/ViewController.m
- README.md
- SwiftVoiceQuickstart/ViewController.swift
- Update descriptions for the `Server` component
- Fix access token sample code to match the instructions
> Update instructions and sample

- Server/functions/place-call.js
…eturn ealier than client.calls.create
> Remove callback(null, null); at the end to avoid returning before the call is created

- Server/functions/place-call.js
> Remove empty line at the end of the place-call function

- README.md
> Use absolute link to the AuioDevice example

- VoiceQuickstart.xcworkspace/xcshareddata/swiftpm/Package.resolved
> Use Voice iOS 6.5.0

- ObjcVoiceQuickstart.xcodeproj/project.pbxproj
> VBLOCKS-XXXX pin to 6.5.2

- ObjcVoiceQuickstart.xcodeproj/project.pbxproj
> VBLOCKS-XXXX Revert pin to 6.5.2

- README.md
> Add VoIP certificate instruction to exclude the cert header (bag attributes)

- VoiceQuickstart.xcworkspace/xcshareddata/swiftpm/Package.resolved
> Use Voice iOS 6.8.0

- VoiceQuickstart.xcworkspace/xcshareddata/swiftpm/Package.resolved
> Use Voice iOS 6.8.1

- README.md
> Add note to remind developers to use their own TwiML app URL

- ObjcVoiceQuickstart/ViewController.m
- SwiftVoiceQuickstart/ViewController.swift
- VoiceQuickstart.xcworkspace/xcshareddata/swiftpm/Package.resolved
Update to 6.9.0 and default logger example.
> VBLOCKS-1657 update to 6.9.0 and default logger example.

- VoiceQuickstart.xcworkspace/xcshareddata/swiftpm/Package.resolved
> Update SPM to Vocie iOS 6.9.1

- ObjcVoiceQuickstart/ViewController.m
- SwiftVoiceQuickstart/ViewController.swift
- VoiceQuickstart.xcworkspace/xcshareddata/swiftpm/Package.resolved
> Use Voice iOS 6.9.2

- README.md
Updated outdated links that were leading to redirects in /docs pages.
> [DEVEDSB-1781] Fix outdated links

- README.md
> Add workaround instruction for legacy certificate
