twilio/voice-quickstart-ios

- Podfile
- SwiftVoiceQuickstart/Info.plist
- SwiftVoiceQuickstart/ViewController.swift
The latest Voice SDK has consolidated the `TVOIncomingCall` & `TVOOutgoingCall` objects into an unified `TVOCall` object. A new `TVOCallInvite` object is also introduced to abstract the incoming attributes from the original `TVOIncomingCall` object.
Also added some sample code to demonstrate how to use the `TVOCall.disconnect` method to hang up the call properly.
> Update for new SDK Call object model

- SwiftVoiceQuickstart/ViewController.swift
No need to wait until the incoming ringtone to finish playing before accepting the call invite.
> Terminate incoming ringtone playback immediately

- Podfile
- SwiftVoiceCallKitQuickstart/ViewController.swift
- SwiftVoiceQuickstart/ViewController.swift
The `TVOCall` object for the first parameter of the `call:didFailWithError:` method was changed to optional last time, but missed to update the one in regular quickstart. CallKit one was updated last time.
> For Voice 2.0.0-beta12

- Podfile
Consume 2.0.0-beta13, which does not require any code changes. I specified the platform at the target level to suppress CocoaPods warnings.
> [!] Automatically assigning platform ios with version 8.1 on target ObjCVoiceQuickstart because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
> 
> [!] Automatically assigning platform ios with version 10.0 on target ObjCVoiceCallKitQuickstart because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
>
> Bump to 2.0.0-beta13

- SwiftVoiceCallKitQuickstart/ViewController.swift
#56 
Use the `reportOutgoingCallWithUUID:connectedAtDate:` method to notify the (CallKit) system that the call is now connected otherwise the system will treat it as a canceled call even if the call was accepted and connected.
> Issue56 - report call when connected

- README.md
The workspace to use is `SwiftVoiceQuickstart.xcworkspace` not `SwiftCVoiceQuickstart.xcworkspace`
> Fix workspace name typo

- Podfile
- SwiftVoiceCallKitQuickstart/ViewController.swift
- SwiftVoiceQuickstart/ViewController.swift
- Podspec version bumped
- The `callInviteReceived:` method is now called for both `TVOCallInviteStatePending` and `TVOCallInviteStateCanceled` states and the original `callInviteCanceled:` method is removed from the `TVONotificationDelegate` protocol
> Updates for Voice 2.0.0-beta17 release

- Podfile
- SwiftVoiceCallKitQuickstart/ViewController.swift
- SwiftVoiceQuickstart/ViewController.swift
- Update Podfile version
- Return value of `TwilioVoice.call()` and `TVOCallInvite.accept()` are now `nonnull` in beta21.
- In the CallKit sample, use `TwilioVoice.call:params:uuid:delegate:` to provide proper UUID from the action. Also implemented the `provider:performSetHeldCallAction:` method to demo the newly added set-hold function of `TVOCall`.
> Update for Voice 2.0.0-beta21

- README.md
In case the user is using the [PHP Server Quickstart](https://github.com/twilio/voice-quickstart-server-php), mention adding `.php` extension for endpoints in README.
> Php extension

- README.md
As noted in an email to existing customers in early April, due to a phased roll out of certain SSL certificates, these versions will stop working after September 18, 2018.
> Deprecation notice for versions 2.0.0-beta9 to 2.0.0-beta12

- SwiftVoiceCallKitQuickstart/ViewController.swift
- SwiftVoiceQuickstart/ViewController.swift
The `pushRegistry:didReceiveIncomingPushWithPayload:forType:withCompletionHandler:` is available on iOS 11 and above. The original `pushRegistry:didReceiveIncomingPushWithPayload:forType:` [will soon be deprecated by Apple](https://developer.apple.com/documentation/pushkit/pkpushregistrydelegate/1614492-pushregistry?language=swift).
The `pushRegistry:didReceiveIncomingPushWithPayload:forType:withCompletionHandler:` method will be called if both the methods exist.
Note: calling the `TwilioVoice.handleNotification()` method is guaranteed to get at least one of the `TVONotificationDelegate` callback immediately, so it is safe to call the completion handler right after calling `TwilioVoice.handleNotification()`.
> New PushKit delegate method for iOS 11

- Podfile
- README.md
- SwiftVoiceCallKitQuickstart/AppDelegate.swift
- SwiftVoiceCallKitQuickstart/ViewController.swift
- SwiftVoiceQuickstart.xcodeproj/project.pbxproj
- SwiftVoiceQuickstart/AppDelegate.swift
- SwiftVoiceQuickstart/ViewController.swift
This pull request is to apply updates to accommodate API changes in Voice SDK 3.0.0-preview1. For more details, checkout the changelog of the [Programmable Voice iOS SDK](https://www.twilio.com/docs/voice/voip-sdk/ios/changelog).
Update for Voice iOS 3.0.0-preview1
- `[TwilioVoice version]` is now `[TwilioVoice sdkVersion]` to avoid method ambiguity with `NSObject`.
- Update log level.
- Use `TwilioVoice.audioDevice` and `TVODefaultAudioDevice` for AVAudioSession configuration and audio start/stop for CallKit integration.
- In `pushRegistry:didReceiveIncomingPushWithPayload:forType:withCompletionHandler:` callback, fulfill the completion in the main queue to ensure the incoming call can be reported to CallKit and show the system call UI if the app was previously terminated.
- Use new …
> Update for Voice 3.0.0-preview1

- Podfile
- README.md
- SwiftVoiceCallKitQuickstart/ViewController.swift
- SwiftVoiceQuickstart/ViewController.swift
- Use `3.0.0-preview3` in `Podfile`.
- Adopt the new `TVOCallInvite` and `TVOCancelledCallInvite` object model.
- `TVOCallInviteState` is removed and the new `TVOCancelledCallInvite` object is introduced.
- Adopt the new `TVONotificationDelegate`
- `notificationError:` has been removed in `3.0.0-preview3`.
- `cancelledCallInviteReceived:` method added for `TVOCancelledCallInvite`.
> Updates for 3.0.0-preview3

- SwiftVoiceCallKitQuickstart/ViewController.swift
Update the end-call flow to avoid requesting the end-call action twice.
Related issue: #155
> Fix end-call flow to avoid unknown UUID error

- SwiftVoiceCallKitQuickstart/ViewController.swift
Update the end-call flow to avoid requesting the end-call action twice.
Related issue: #155
> (3.x) Fix end-call flow to avoid unknown UUID error

- README.md
Migration guide from 2.x to 3.x
- `TVOCallInvite` Changes
- Specifying a media region
- `TVOConnectOptions` & `TVOAcceptOptions`
- Ringing
- Audio Device
- Custom Parameters
> Add migration guide from 2.x to 3.x

- Cartfile
- Podfile
- README.md
https://www.twilio.com/docs/voice/voip-sdk/ios/3x-changelog#300-beta1-november-26-2018
* Programmable Voice iOS SDK 3.0.0-beta1 [[Carthage]](https://www.twilio.com/docs/voice/voip-sdk/ios#carthage), [[Cocoapods]](https://www.twilio.com/docs/voice/voip-sdk/ios#cocoapods), [[Dynamic Framework]](https://media.twiliocdn.com/sdk/ios/voice/releases/3.0.0-beta1/twilio-voice-ios-3.0.0-beta1.tar.bz2), [[Static Library]](https://media.twiliocdn.com/sdk/ios/voice/releases/3.0.0-beta1/twilio-voice-ios-static-3.0.0-beta1.tar.bz2), [[docs]](https://media.twiliocdn.com/sdk/ios/voice/releases/3.0.0-beta1/docs/).
Enhancements
- Added media and signaling related error codes.
Known Issues
- CLIENT-4943 Restrictive networks may fail unless ICE servers are provided via `TVOConnectOptions` or …
> Using 3.0.0-beta1

- README.md
- SwiftVoiceCallKitQuickstart/ViewController.swift
- SwiftVoiceQuickstart/ViewController.swift
Add a section in the migration guide for requesting microphone permission in the apps using 3.x SDK.
> Add microphone permission guideline in the migration guide

- SwiftVoiceCallKitQuickstart/ViewController.swift
- SwiftVoiceQuickstart/ViewController.swift
Save the completion handler of the `pushRegistry:didReceiveIncomingPushWithPayload:forType:withCompletionHandler:` method and call when the call is properly reported to CallKit.
Related issues: #188, #174, #152
> Call the incoming push completion handler when call reported to CallKit

- Cartfile
- Podfile
- README.md
* Programmable Voice iOS SDK 3.0.0-beta4 [[Carthage]](https://www.twilio.com/docs/voice/voip-sdk/ios#carthage), [[Cocoapods]](https://www.twilio.com/docs/voice/voip-sdk/ios#cocoapods), [[Dynamic Framework]](https://media.twiliocdn.com/sdk/ios/voice/releases/3.0.0-beta4/twilio-voice-ios-3.0.0-beta4.tar.bz2), [[Static Library]](https://media.twiliocdn.com/sdk/ios/voice/releases/3.0.0-beta4/twilio-voice-ios-static-3.0.0-beta4.tar.bz2), [[docs]](https://media.twiliocdn.com/sdk/ios/voice/releases/3.0.0-beta4/docs/).
Enhancements
- API Changes
- `TVOCallFeedbackScoreNoScore` is replaced with `TVOCallFeedbackScoreNotReported`.
Known Issues
- CLIENT-5578 WiFi to WiFi handover may disconnect the Call.
- CLIENT-4943 Restrictive networks may fail …
> Update for 3.0.0-beta4 release

- Cartfile
- Podfile
- README.md
Enhancements
- CLIENT-5678 The size impact report now includes both armv7 and arm64 architectures.
- The `libboringssl.a` library is now separated and shipped alongside the static library `libTwilioVoice.a`. Add `-lboringssl` in the **Other Linker Flags** to link the SDK properly.
Bug Fixes
- CLIENT-5664 The static library `libTwilioVoice.a` is now properly linked with dependencies.
Known Issues
- CLIENT-5578 WiFi to WiFi handover may disconnect the Call.
- CLIENT-4805 The SDK size is significantly larger than 2.x. …
> Update for 3.0.0-beta5 release

- Cartfile
- Podfile
- README.md
Enhancements
- API Changes
- The `from` property of the `TVOCallInvite` and `TVOCancelledCallInvite` objects is now `nullable` in case the value is not available in the call invite notification.
Bug Fixes
- CLIENT-5801 Fixed an issue where an incoming call invite that did not contain a from field was not considered a valid notification.
Known Issues
Size Report …
> Use Voice iOS 3.0.0-beta7

- Cartfile
- Podfile
- README.md
Bug Fixes
- CLIENT-5796 Fixed an issue where the millisecond timestamp in the Insights event payload overflows on 32-bit architecture devices.
- CLIENT-5830 Removed scripts from `TwilioVoice.framework` that could cause code signing issue when uploading apps to iTunes Connect.
Known Issues
Size Report
> Use Voice iOS 3.0.0-beta8

- Cartfile
- Podfile
- README.md
Enhancements
- CLIENT-5806 CLIENT-5807 Updated the API documentation for `[TVOCallInvite acceptWithDelegate:]` and `[TVOCallInvite acceptWithOptions:delegate:]`.
- CLIENT-5810 Updated the API documentation for `TVOCall`.
- API Changes
- Attempts to connect a Call via `[TwilioVoice connectWithDelegate:]` or `[TVOCallInvite acceptWithDelegate:]` that fail prior to reaching the `TVOCallStateConnected` state will always result in the `call:didFailToConnectWithError:` callback with an error code. However, if `[TVOCall disconnect]` is called while an attempt to connect or accept a call is made, the `call:didDisconnectWithError:` callback will be raised with no error.
Bug Fixes
- CLIENT-5813 Network loss scenarios that resulted in a Call failure now raise the `call:didFailToConnectWithError:` …
> Use 3.0.0-beta9

- Cartfile
- Podfile
- README.md
Bug Fixes
- CLIENT-5828, CLIENT-5868 A network change that occurs during a reconnection will now trigger another reconnection attempt ensuring media is restored on the correct network.
- CLIENT-5882 Call metrics insights will always be available after a network handover when the call is in `TVOCallStateConnected` state.
Known Issues
Size Report
armv7 | 3.0 MB | …
> Use Voice iOS 3.0.0-beta10

- Cartfile
- Podfile
- README.md
Enhancements
- CLIENT-5973 Removed `TVOErrorConnectionTimeoutError`, `TVOErrorSignalingConnectionError`, `TVOErrorSignalingConnectionTimeoutError`, `TVOErrorSignalingIncomingMessageInvalidError`, `TVOErrorSignalingOutgoingMessageInvalidError`, `TVOErrorConfigurationAcquireFailedError` and `TVOErrorConfigurationAcquireTurnFailedError` from `TVOError.h`.
Bug Fixes
- CLIENT-5935 Fixed a bug where constant audio level warning events are being sent to Insights when the call is muted or onhold.
- CLIENT-5969 Renamed `kDefaultAVAudioSessionConfigurationBlock` to `kTVODefaultAVAudioSessionConfigurationBlock` so that `TwilioVoice.framework` and `TwilioVideo.framework` may be used in the same application.
- CLIENT-5977 Fixed a bug where the SDK was sending double values for `packets_lost_fraction` …
> Use Voice iOS 3.0.0-beta12

- Cartfile
- Podfile
- README.md
Bug Fixes
- CLIENT-5982 Fixed a bug where call quality warnings might be sent to Insights multiple times before the warning is cleared.
Known Issues
Size Report
Universal | 5.8 MB | 12.3 MB
> Use Voice iOS 3.0.0-beta13

- Cartfile
- Podfile
- README.md
- SwiftVoiceCallKitQuickstart/ViewController.swift
- SwiftVoiceQuickstart/ViewController.swift
API Changes
- CLIENT-5588 Added new state `TVOCallStateReconnecting` to indicate that the Call is reconnecting due to network change or lost. New callback methods `call:isReconnectingWithError:` and `callDidReconnect:` are added to the `TVOCallDelegate` protocol to provide state transitions.
> Updates for using Voice iOS 4.0.0

- Cartfile
- Podfile
Enhancements
- CLIENT-6420 The static library dependencies are now embedded in `libTwilioVoice.a`
- The `libboringssl.a` library is now separated and shipped alongside the static library `libTwilioVoice.a`. Add `-lboringssl` in the **Other Linker Flags** to link the SDK properly.
- CLIENT-6438 Added `customParameters` property to `TVOCancelledCallInvite`.
Pass custom parameters in TwiML
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Response>
<Dial callerId="client:alice">
<Client>
<Identity>bob</Identity>
<Parameter name="caller_first_name" value="alice" />
<Parameter name="caller_last_name" value="smith" />
</Client>
</Dial>
</Response>
```
`cancelledCallInvite.customParameters`:
```objc
{
"caller_first_name" = "alice";
"caller_last_name" = "smith";
}
```
Known Issues
- CLIENT-4943 …
> Use Voice iOS 4.2.0

- SwiftVoiceCallKitQuickstart/ViewController.swift
- SwiftVoiceQuickstart/ViewController.swift
The iOS SDK that comes with Xcode 11 beta is updating the data structure of the PushKit device token. This PR updates the way of decoding the device token data returned from the `pushRegistry:didUpdatePushCredentials:forType:` callback. The same decoding implementation works for both iOS 13 SDK (Xcode 11) and earlier (Xcode 10 and iOS 12)
Note that with the coming release of iOS 13, using PushKit without CallKit (the `ObjCVoiceQuickstart` project) will cause runtime exception and application crash.
> Update PushKit device token decoding

- Podfile
- README.md
- SwiftVoiceCallKitQuickstart.xcodeproj/project.pbxproj
- SwiftVoiceCallKitQuickstart/ViewController.swift
- SwiftVoiceQuickstart.xcodeproj/project.pbxproj
- SwiftVoiceQuickstart/ViewController.swift
- Update Podfile to use Voice iOS 2.1.0
- Update README with migration guide
- Use Swift 4.0 compiler
- Code changes
- Update device token decoding 
- Update the mechanism to fulfill the incoming-push completion: now the Voice SDK processes and return a `TVOCallInvite` object synchronously, report the call to CallKit and fulfill the completion before existing the method
> Voice iOS 2.1.0 updates

- SwiftVoiceQuickstart/ViewController.swift
Keep the call object as property instance to ensure the call connection can be established when it's out of method scope.
> Use property instance to explicitly keep the call objects

- README.md
The quotes can be misleading into including them when setting up the .env variables
> Removed the quotes from the .env variables. They can be misleading.

- Podfile
Bug Fixes in Voice iOS 2.1.1
- [CLIENT-6896] Fixed an issue which caused call accept failure. This occurred when the user denied mic access on an incoming call. With this change, mic permissions are no longer requested on an incoming call. They are  requested when the user accepts the call.
> Update Podfile for referencing the latest 2.1 Voice iOS SDK

- Cartfile
- Podfile
- Incoming call handling improvements. Previously, if we encountered network issues before an incoming call was answered or rejected, we disconnected the call. With this release, we will continue to try and establish a connection to Twilio for a maximum of 40 seconds before we disconnect the call.
- We added support for OpenSSL 1.1.x in the static library version of our SDK. To use this flavor of the SDK, please refer to the instructions included in the [Static Library](https://github.com/twilio/twilio-voice-ios/releases/download/5.1.0/libTwilioVoice.zip)
- We now publish the negotiated codec and its associated parameters to Insights.
| Event Group | Level | Event Name | Description |
|-------------|-------|------------|-------------|
| settings    | INFO  | codec      | Raised when the …
> Use Voice iOS 5.1.0

- SwiftVoiceQuickstart/ViewController.swift
The current sample code assumes that only one call or call invite is is supported at the same time and therefore will not report the VoIP incoming call push notification to CallKit when there is already a pending invite or an active call.
This PR modifies the sample code to be able to handle multiple calls or call invites and ensures that VoIP push notifications are always reported to CallKit as new incoming calls.
This table illustrates how the updated sample app behaves in different call scenarios (all with CallKit integrated):
|     | Scenario | Result |
| --- | -------- | ------ |
| ✅A | Alice calls Bob.<br /> Bob does not accept and let ring.<br />Charlie calls Bob.<br />Bob accepts the call. | Alice and Bob talking.<br />Bob won't see Charlie's incoming call.<br />Charlie was hung …
> Make quickstart capable of handling multiple calls or call invites

- SwiftVoiceQuickstart/ViewController.swift
The audio-device toggling in the `provider:performEndCallAction:` delegate method would cause the audio engine to print out error messages like these:
```
provider:didDeactivateAudioSession:
[aurioc] AURemoteIO.cpp:1086:Initialize: failed: 561017449 (enable 3, outf< 1 ch,  16000 Hz, Int16> inf< 1 ch,  16000 Hz, Int16>)
[aurioc] AURemoteIO.cpp:1086:Initialize: failed: 561017449 (enable 3, outf< 1 ch,  16000 Hz, Int16> inf< 1 ch,  16000 Hz, Int16>)
[aurioc] AURemoteIO.cpp:1086:Initialize: failed: 561017449 (enable 3, outf< 1 ch,  16000 Hz, Int16> inf< 1 ch,  16000 Hz, Int16>)
[aurioc] AURemoteIO.cpp:1086:Initialize: failed: 561017449 (enable 3, outf< 1 ch,  16000 Hz, Int16> inf< 1 ch,  16000 Hz, Int16>)
[aurioc] AURemoteIO.cpp:1086:Initialize: failed: 561017449 (enable 3, outf< 1 ch,  16000 …
```
> Remove audio device toggling when ending CallKit calls

- Podfile
* Programmable Voice iOS SDK 5.1.2 [[Carthage]](https://www.twilio.com/docs/voice/voip-sdk/ios#carthage), [[Cocoapods]](https://www.twilio.com/docs/voice/voip-sdk/ios#cocoapods), [[Dynamic Framework]](https://github.com/twilio/twilio-voice-ios/releases/download/5.1.2/TwilioVoice.framework.zip), [[Static Library]](https://github.com/twilio/twilio-voice-ios/releases/download/5.1.2/libTwilioVoice.zip), [[docs]](https://twilio.github.io/twilio-voice-ios/docs/5.1.2/).
Bug Fixes
- Fixed a crash when a canceled call invite is received and the `from` value is `nil`.
Universal | 6.0 MB | 12.6 MB
> Updates for Voice iOS 5.1.2 release

- ObjcVoiceQuickstart/AppDelegate.h
- ObjcVoiceQuickstart/AppDelegate.m
- ObjcVoiceQuickstart/ViewController.h
- ObjcVoiceQuickstart/ViewController.m
- SwiftVoiceQuickstart/AppDelegate.swift
- SwiftVoiceQuickstart/ViewController.swift
The changes in this PR demonstrate the best practice of how an application should perform registration in order to subscribe for incoming call push notifications.
- Move `PkPushRegistry` instance initialization and `PkPushRegistryDelegate` methods to `AppDelegate`. This ensures that PushKit is set up each time the app is launched and push notifications can be received by the application.
- Events of the `PkPushRegistryDelegate` protocol will be sent to the view-controller via the `PushKitEventDelegate` protocol. This could be implemented in the best place based on the app logic.
- Upon receiving the `didUpdatePushCredentials:` callback, the app can use the cached device token that was saved in a previous successful registration and only call `TwilioVoice.register()` only when the device …
> Demonstrate the best practice of performing registration

- Podfile
Enhancements
- Attempts to re-establish the media connection will be done preemptively if no media flow is detected for 3 seconds.
- Media connecion of an ongoing `Call` switches to a lower cost network when available.
- Proper data types are added to the Insights event payload.
Bug Fixes
- Fixed a crash when a canceled call invite is received but the `from` value is `nil`.
Things to Note
- Since media and signaling reconnect are two completely separate processes, it is likely that for a single network change event multiple `[TVOCallDelegate call:isReconnectingWithError:]` and `[TVOCallDelegate callDidReconnect:]` callbacks will be received in the order specified i.e a `[TVOCallDelegate call:isReconnectingWithError:]` callback will always be followed by a `[TVOCallDelegate …
> Use Voice iOS 5.2.0

- SwiftVoiceQuickstart/ViewController.swift
Made some enhancements to the Starter Project code so that there is a more descriptive structure to the code, as well as some refactoring with use of some more "modern" Swift code. That way, other developers can more easily use (or even copy) some code to their own projects without doing *too* much refactoring themselves. 😉 
The enhancements in detail:
- Removed some unnecessary parentheses and references to `self.` (as most of the time, Swift can infer it itself and the syntax highlighting in Xcode cues for an instance member)
- Removed some unnecessary type annotations (Again, Swift can infer most things and it makes the code more readable and concise)
- Removed `break`s in `switch case` statements (Swift `cases` don't automatically fall through)
- Used `guard` instead of `if` e.g. for …
> Made the starter code more "Swifty"

- ObjcVoiceQuickstart/ViewController.m
- Podfile
- README.md
- SwiftVoiceQuickstart/ViewController.swift
- Use Voice iOS 5.3.0
- Use new registration methods that takes `NSData` for the PushKit device token
> Updates for using Voice iOS 5.3.0

- README.md
Updated VoIP certificate private/public key extraction instructions to match the instructions for extracting keys from regular push certificates - https://www.twilio.com/docs/notify/configure-ios-push-notifications#create-a-certificate-key. Fixes "unable to load Private Key" when trying to extract the private key during the `openssl rsa` command.
> Fix VoIP certificate key extraction instructions

- Podfile
* Programmable Voice iOS SDK 5.3.1 [[Carthage]](https://www.twilio.com/docs/voice/voip-sdk/ios#carthage), [[Cocoapods]](https://www.twilio.com/docs/voice/voip-sdk/ios#cocoapods), [[Dynamic Framework]](https://github.com/twilio/twilio-voice-ios/releases/download/5.3.1/TwilioVoice.framework.zip), [[Static Library]](https://github.com/twilio/twilio-voice-ios/releases/download/5.3.1/libTwilioVoice.zip), [[docs]](https://twilio.github.io/twilio-voice-ios/docs/5.3.1/).
Improvements
- Optimized `[TwilioVoice unregisterWithAccessToken:deviceTokenData:completion:]` by reducing the number of network requests.
- Added background handling support to `[TwilioVoice registerWithAccessToken:deviceTokenData:completion:]` and `[TwilioVoice unregisterWithAccessToken:deviceTokenData:completion:]`. They will …
> Use Voice iOS 5.3.1

- ObjcVoiceQuickstart/Base.lproj/Main.storyboard
- ObjcVoiceQuickstart/ViewController.m
- SwiftVoiceQuickstart/Base.lproj/Main.storyboard
- SwiftVoiceQuickstart/ViewController.swift
Note: the changes in this PR use a version of the Voice SDK that is in development.
This PR uses the `[TVOCallDelegate call:didReceiveQualityWarnings:previousWarnings]` to receive updates about the newly raised or cleared quality warnings and display in the UI.
A toaster showing a warning detected
<kbd><img width=300px src="https://user-images.githubusercontent.com/16326574/79299153-2a6aea00-7e98-11ea-9ad8-8b69f52e069c.PNG"/></kbd>
> Use the quality warning callback to show newly detected/cleared warnings

- Podfile
* Programmable Voice iOS SDK 5.5.1 [[Carthage]](https://www.twilio.com/docs/voice/voip-sdk/ios#carthage), [[Cocoapods]](https://www.twilio.com/docs/voice/voip-sdk/ios#cocoapods), [[Dynamic Framework]](https://github.com/twilio/twilio-voice-ios/releases/download/5.5.1/TwilioVoice.framework.zip), [[Static Library]](https://github.com/twilio/twilio-voice-ios/releases/download/5.5.1/libTwilioVoice.zip), [[docs]](https://twilio.github.io/twilio-voice-ios/docs/5.5.1/).
Bug Fixes
- Fixed the background task handling in `[TVOCall disconnect]`, `[TVOCallInvite reject]`, `[TwilioVoice registerWithAccessToken:deviceTokenData:completion:]` and `[TwilioVoice unregisterWithAccessToken:deviceTokenData:completion:]`. iOS should no longer report a background task risk of termination warning.
- Fixed a …
> Use Voice iOS 5.5.1

- AudioDeviceExample/ViewController.swift
- ObjcVoiceQuickstart/ViewController.m
- Podfile
API Change
- The Voice SDK has been updated for better Swift interoperability.
- The `TVO` prefix has been removed from all Twilio Voice types
- Many of the delegate function declarations have been revamped for better clarity of their intent
- Some of the class method declarations have been revamped for better clarity of their intent
- This release has improved API for CallKit integration. In order to use CallKit with SDK, you must set `ConnectOptions.uuid` or `AcceptOptions.uuid` while making or answering a Call. When `ConnectOptions.uuid` or `AcceptOptions.uuid` is set, it is your responsibility to enable and disable the audio device. You should enable the audio device in `[CXProviderDelegate provider:didActivateAudioSession:]`, and disable the audio device in `[CXProviderDelegate …
> Use Voice iOS 6.0.0

- Docs/verified-caller-number.md
- ObjcVoiceQuickstart/ViewController.m
- SwiftVoiceQuickstart/ViewController.swift
Refactoring the `CXProvider` initialization to avoid CallKit call flow going into coma state when submitting requests.
> Keep one CXProvider initialization to avoid CallKit coma situation

- ObjcVoiceQuickstart/ViewController.m
- SwiftVoiceQuickstart/ViewController.swift
Changing the logic about when app should register -
1. Saving date and time of the last successful registration.
2. Since the registration binding is valid for 365 days, forcing registration if last registration was made > 365 days (cc @idelgado ?) 
> CLIENT-8135 - Saving registration binding date and time in user defaults

- AudioDeviceExample/ViewController.swift
- ObjcVoiceQuickstart/AppDelegate.m
- ObjcVoiceQuickstart/ViewController.m
- Podfile
- SwiftVoiceQuickstart/AppDelegate.swift
- SwiftVoiceQuickstart/ViewController.swift
- Private IP addresses are masked in Release mode for the SDK logs and the `ice-candidate` Insights event payload.
- Private IP addresses will not be masked in `Debug` mode. The `selected-ice-candidate-pair` event will contain private IP address of the local active ICE candidate for debugging purpose in both Release and Debug modes.
- Fixed a bug where caller might not receive the `call:didDisconnectWithError:` callback when the callee hangs up. 
- Fixed a bug where callee was not receiving the `cancelledCallInviteReceived:error:` callback when signaling connection error happens.
- The Voice SDK had the same `TwilioVoice` framework name and the class name. This was causing swift compile time errors when an app tries to access a TwilioVoice framework's class using the module name, e.g. …
> Voice ios 6.1.0

- ObjcVoiceQuickstart/ViewController.m
- SwiftVoiceQuickstart/ViewController.swift
Remove invite object from active-invite array when the call is canceled to avoid a redundant `invite.reject()` call in the CallKit `provider:performEndCallAction:` callback, which could be fired when the user actively rejects the call from the system Call app UI.
Without removing the invite, the `invite.reject()` would result in a `410 Gone` error since in the case of the call being hung up by the remote party the call which the SDK is trying to reject is already gone.
Without the updates, the SDK receives a `410 Gone` error after calling `reject()` while the call has been ended (CA1f8acd4e3acb20c8a8966da75c2c5448). No more `reject` and `410 Gone` error after patched (CA4fe1bc8ad364053b987434e6c2afdc24).
> Remove invite object from active-invite array when the call is canceled

- Podfile
* Programmable Voice iOS SDK 5.5.2 [[Carthage]](https://www.twilio.com/docs/voice/voip-sdk/ios#carthage), [[Cocoapods]](https://www.twilio.com/docs/voice/voip-sdk/ios#cocoapods), [[Dynamic Framework]](https://github.com/twilio/twilio-voice-ios/releases/download/5.5.2/TwilioVoice.framework.zip), [[Static Library]](https://github.com/twilio/twilio-voice-ios/releases/download/5.5.2/libTwilioVoice.zip), [[docs]](https://twilio.github.io/twilio-voice-ios/docs/5.5.2/).
Bug Fixes
- Fixed a potential crash in the core module where the logger could be accessed after being destroyed by another thread. [#419](https://github.com/twilio/voice-quickstart-ios/issues/419)
- Fixed a bug where caller might not receive the `[TVOCallDelegate call:didDisconnectiWithError:]` callback when callee hangs up.
- …
> (5.x) Use Voice iOS 5.5.2

- VoiceQuickstart.xcworkspace/xcshareddata/swiftpm/Package.resolved
Enhancements
- This release is based on Chromium WebRTC 88.
- The simulator `arm64` architecture on Apple Silicon Macs is now available.
- The SDK uses Unified Plan SDP semantics instead of Plan-B.
Known Issues
- Carthage is not currently a supported distribution mechanism for Twilio Voice. Carthage does not currently work with `.xcframeworks` as documented [here](https://github.com/Carthage/Carthage/issues/2890). Once Carthage supports binary `.xcframeworks`, Carthage distribution will be re-added.
Size Impact for 6.3.0
Architecture | Compressed Size | Uncompressed Size
arm64 | 3.2 MB | 7.1 MB
> Use Voice iOS 6.3.0

- VoiceQuickstart.xcworkspace/xcshareddata/swiftpm/Package.resolved
* Programmable Voice iOS SDK 6.3.1 [[XCFramework]](https://github.com/twilio/twilio-voice-ios/releases/download/6.3.1/TwilioVoice.xcframework.zip) (checksum: 08e5839eb77d8746baff8b132059f0babfb9e1ed860903553b7d9c02411442af
).
Enhancements
- The Voice SDK now validates full remote domain names while setting up the TLS connection.
- The Voice SDK now uses the maximum timeout value 10 minutes to answer an incoming call.
Architecture | Compressed Size | Uncompressed Size
arm64 | 3.2 MB | 7.0 MB
> Use Voice iOS 6.3.1

- Docs/push-credentials-via-notify-api.md
- README.md
- Instruction and sample code showing how to manage Push Credentials (for regional) using the Notify Credential Resource API
- Reference link in the README
Note that this page will be referenced in the changelog when the regional feature is released.
> Instructions to manage push credentials using the Notify Credential Resource API

- SwiftVoiceQuickstart/Base.lproj/Main.storyboard
- SwiftVoiceQuickstart/ViewController.swift
Add support for handling multiple Voice SDK calls at the same time.
- Set the [maximumCallGroups](https://developer.apple.com/documentation/callkit/cxproviderconfiguration/1648348-maximumcallgroups) property to "2" to allow swapping between multiple Voice SDK calls.
- Add tracking of the UISwitch states when switching between multiple ongoing calls
- Fix constraint error for the Quality Warning label
- Fix invalid `callIsReconnecting` delegate method name
- Add workaround for an iOS bug when un-holding a VoIP call after an ended PSTN call (https://developer.apple.com/forums/thread/694836)
> Add support for multiple call handling

- AudioDeviceExample/ViewController.swift
- ObjcVoiceQuickstart/ViewController.m
- SwiftVoiceQuickstart/ViewController.swift
- Fix an issue when the alert message that is shown when denying the microphone usage permission was not being presented on the main thread, resulting in a crash.
- Add support for sending DTMF via [performPlayDTMFCallAction](https://developer.apple.com/documentation/callkit/cxproviderdelegate/provider(_:perform:)-4htxt?changes=_3&language=objc)
> Ensure UI is updated on the main thread when denying mic permission and add support for sending DTMF
